language: ruby
rvm:
- 2.3.1
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: make build && make test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
secure: "EjqphnvvBko3/Oqh4OlXsk0+F0lhBA5fl2wPAQVrnHE60AiC+aaUd7rPEPTyH5xmxhjn2njc7jQXFB5dLRMzc+4WTuBKixhr8E1txWCuNvCuM6QbffnBjBUKkz0pu+OOKGcGg1NsjDxPT/EtCXEsYVPIUsPV96MraMLFXOoDypdqdH033MMoPA2XUubNkUpI2sc5Re7XEBmyAERjx1wAEt15q4NYc5Bro6V5cytBQ4hw6TL2u7zXcImJ71AOMBHmazMcYfAp++gDBDvC2HNRIvDNmsgMNOGMvl3eF4NpYBaWmWNJSXeQUteH+ixT9XsuboGohL6LeWX0yLCwX9paJ07NEc3THHT70uJ6sms7kLKrQDsv4DlXaT2iEF/pCojL54PuBCVoDsSozooHrQ4xt9Xn84USHLVzSwIgSFZwz6GztsFf5OfUrmuqhD7vJW2n0V5WM50gPABJa6yyZtjIOxZFxsZs3bezdN8ts++UtkMwctTTWKN0o9TfMGbQ49wTaJLvc+9CLIlJHvN/vPIe2irX1IjTiQ2DU0KDLnhO53nJ0/l7jVlP2ezf4kXlp+fg7WKmrGbg6x0ynRyJ5tykprndpmikaFmURIe85KnmwAkj1EI4pV9wAfSCJV/KfSY52+gSf+oLS8JO/aOCSLntAhhmAQi3zEvMzjd19ml0Yh8="
addons:
  apt:
    packages:
    - sshpass
