name: "Christopher Woodall"
pygments: true
description: "Embedded Systems Engineer, Musician and Rock Climber"
base_url: http://localhost:4000
portfolio_tags: ['electronics', 'robotics', 'web_design','software', 'music', 'mechanical', 'other']
url: "http://localhost:4000"
exclude: ["Makefile"]
ftp_host: happyrobotlabs.com
ftp_dir: /public_html/cjwoodall/
