name: "Chris J. Woodall"
pygments: true
description: "Student, Electrical Engineer and General Tinkerer"
base_url: localhost:4000
portfolio_tags: ['electronics', 'robotics', 'web_design','software', 'music', 'mechanical', 'other']
url: "http://cjwoodall.com"
exclude: ["Makefile", "/assets/img/glyphicons"]
ftp_host: happyrobotlabs.com
ftp_dir: /public_html/cjwoodall/
