name: "Chris J. Woodall"
pygments: true
description: "Student, Electrical Engineer and General Tinkerer"
base_url: localhost:4000
portfolio_tags: ['electronics', 'software', 'music', 'mechanical', 'other']
url: "http://localhost:4000"